### ISSUE TITLE
Getting a unspecified version

### ISSUE THREAD

**Issue by AnakinPt** [toolebox-io/gradle-git-versioner#16]
I'm starting to use your plugin to define the version of the software. I don't know what's happening, but I'm getting a version undefined in the middle of the build. Let's say I use:
`
docker {
    name "${project.name}"
    tag 'local', '${project.name}:latest'
    tag 'localVersion', "${project.name}:${version}"
}
`
the $version variable is not set. Also, in this task:
`
task unpack(type: Copy) {
    dependsOn bootJar
    from(zipTree(tasks.bootJar.outputs.files.singleFile))
    into("build/docker/dependency")
}
`
it doesn't find the matching jar, because it generates with the version name but the outputs, the file has no version on the name.

**Comment by Tyrannoseanus** [comment]
This is usually due to trying to use the version before it has been resolved- Gradle does things in a certain order and if you're trying to access the version before the plugin has been applied or before the project has been evaluated, you won't have access to the version. 

https://github.com/toolebox-io/gradle-git-versioner/issues/13 has some additional information that I won't repeat here, but will probably repeat in the README at some point so it's more obvious what's going on.

**Comment by AnakinPt** [comment]
Left comment in the #13. Closing this because it's a duplicate. Thanks
